title: "Buhfur's Wiki"
description: "The wiki for all things linux / IT / Tech related."
remote_theme: just-the-docs/just-the-docs@v0.10.1

# Site location (custom domain at root)
url: "https://ryanm.dev"
baseurl: ""   # MUST be empty for an apex or subdomain custom domain

color_scheme: dark
back_to_top: true
back_to_top_text: "Back to Top"

# Use _docs as your nav source
collections:
  docs:
    output: true
    permalink: /:collection/:path/

just_the_docs:
  collections:
    docs: {}   # no "name" => no extra "DOCS" section header

# Keep root pages out of the sidebar (prevents duplicate top section)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      nav_exclude: true
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

